### ISSUE TITLE
Error while import during abap git

### ISSUE THREAD

**Issue by anuragguptagithub** [alwinvandeput/zscv_search_cds_views#1]
Annotation for AbapCatalog.dataMaintenance does not exist 

Associated entity 'CDS_SQL_VIEW' for 'CDSSQLVIEW' 

Annotation for AbapCatalog.dataMaintenance does not exist 

**"UNION" cannot be used in view entities** 

Annotation for AbapCatalog.dataMaintenance does not exist 

The data source "ZSCV_ABAPVIEWCHILD" does not exist or is not active 

Annotation for AbapCatalog.dataMaintenance does not exist 

The data source "ZSCV_ABAPVIEWPARENT" does not exist or is not active 

The data source "ZSCV_ABAPVIEWHIER" does not exist or is not active 

Annotation for AbapCatalog.dataMaintenance does not exist 

The data source "ZSCV_ABAPVIEWBYVIEWGROUPBY" does not exist or is not active 

Annotation for AbapCatalog.dataMaintenance does not exist 

DDL Source ZSCV_ABAPVIEWBYVIEW could not be activated 

DDL Source ZSCV_ABAPVIEWBYVIEWGROUPBY could not be activated 

DDL Source ZSCV_ABAPVIEWCHILD could not be activated 

DDL Source ZSCV_ABAPVIEWHIER could not be activated 

DDL Source ZSCV_ABAPVIEWPARENT could not be activated 

DDL Source ZSCV_CDSVIEW was activated (error in the dependencies) 

DDL Source ZSCV_CDSVIEWCHILDCDSVIEW was activated (error in the dependencies) 

DDL Source ZSCV_CDSVIEWRELATION was activated (error in the dependencies) 

DDL Source ZSCV_CDSVIEWRELEASESTATUS was activated (error in the dependencies) 

DDL Source ZSCV_DDICVIEWCHILDDDICVIEW was activated (error in the dependencies) 

DDL Source ZSCV_DDICVIEW was activated with warnings

**Comment by alwinvandeput** [comment]
Could you give it a try whether the update fixes the problem?

**Comment by anuragguptagithub** [comment]
Thanks , yes it worked !

**Comment by anuragguptagithub** [comment]
Closing the issue
