### ISSUE TITLE
Runtime error "PERFORM_NOT_FOUND" when double click in the ALV.

### ISSUE THREAD

**Issue by trianta99** [alwinvandeput/zscv_search_cds_views#2]
When double clicking in the ALV a runtime error occurs. Below is the error analysis from ST22.

_Short Text  Call (PERFORM) to a non-existent external routine.  
Runtime Error  PERFORM_NOT_FOUND  
Exception  CX_SY_DYN_CALL_ILLEGAL_FORM  
Program  SAPLSLVC_FULLSCREEN_  

_Error analysis
An exception has occurred in class "CX_SY_DYN_CALL_ILLEGAL_FORM". This exception was not caught
in procedure "IF_SALV_GUI_OM_FULLSCREEN_HUB~USER_COMMAND" "(METHOD)" or propagated by a RAISING clause.
Since the caller of the procedure could not have anticipated this
exception, the current program was terminated.
The reason for the exception occurring was:
The reason for the exception is:
**Program "SAPLSLVC_FULLSCREEN" is trying to execute an external PERFORM: routine "USER_COMMAND" of
program "ZSCV_SEARCH_CDS_VIEWS".
This routine does not exist however**._

**Comment by alwinvandeput** [comment]
Issue fixed by deactivating line: i_callback_user_command = 'USER_COMMAND'
