### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by tschalcktwm** [alwinvandeput/zscv_search_cds_views#3]
Hi,

I am facing an installation issue with this project. CDS View ZSCV_CDSVIEWSOURCEFIELD contains an error: 
Error in SELECTLIST_ENTRY VIEWNAME of entity ZSCV_CDSVIEWSOURCEFIELD
Expression type ARITHMETIC not allowed in function SUBSTRING, parameter 3

Here is the source code error: 
` define view entity ZSCV_CdsViewSourceField
  as

  select from  ddls_ris_index as Field
    inner join ZSCV_CdsView   as CdsView on CdsView.DdlSourceName = Field.ddlsrc_name
{
  key   Field.ddlsrc_name            as DdlSourceName,

  key
        SUBSTRING( Field.used_artifact_fullname,
                   5,
                   INSTR( SUBSTRING(Field.used_artifact_fullname, 5, 100), '\\TY:') - 1 )                          
        as ViewName,

  key   
        SUBSTRING(
          Field.used_artifact_fullname,
          INSTR(
            SUBSTRING(Field.used_artifact_fullname, 5, 100), '\\TY:') + 8 ,
            100)                     as Field,

        Field.used_artifact_fullname as FullFieldName,
        CdsView.AbapViewType

}
where
  //Only fields. Fields contain \TY:<CDS view>\TY:<Field name>
  INSTR(SUBSTRING(Field.used_artifact_fullname,5, 100), '\\TY:') > 0 `

The -1 is not accepted in the following statement: 
`key
        SUBSTRING( Field.used_artifact_fullname,
                   5,
                   INSTR( SUBSTRING(Field.used_artifact_fullname, 5, 100), '\\TY:') - 1 )                          
        as ViewName`

I tried to add ( before and ) after but it still doesn't work. I am working on S4 Hana 2021 FPS02.

Thanks in advance for your help, 

Thibault

**Comment by alwinvandeput** [comment]
Hello Thibault,

I built the query's on S/4HANA 2022, so probably that's not yet supported on version 2021.

I think we have to split that query into 2 queries, so that this part
`INSTR( SUBSTRING(Field.used_artifact_fullname, 5, 100), '\\TY:') - 1`
wil be calculated in a new CDS view, which will be called from the ZSCV_CdsViewSourceField.

Could you test whether the changes below works on your S/4HANA 2021 system?

```
define view entity ZSCV_CdsViewSourceField_Pos
  as

  select from  ddls_ris_index as Field
{
  key used_artifact_fullname,
  key ddlsrc_name,

      INSTR(SUBSTRING(Field.used_artifact_fullname,5, 100), '\\TY:') as IsFieldInd,

      INSTR(SUBSTRING(Field.used_artifact_fullname, 5, 100), '\\TY:') - 1 as ViewNameEndPos,
  
      INSTR(SUBSTRING(Field.used_artifact_fullname, 5, 100), '\\TY:') + 8  as FieldStartPos
      
}
```

And if that one works, adjust the ZSCV_CdsViewSourceField to 

```
  select from  ZSCV_CdsViewSourceField_Pos as Field
    inner join ZSCV_CdsView                as CdsView on CdsView.DdlSourceName = Field.ddlsrc_name
{
  key   Field.ddlsrc_name            as DdlSourceName,

  key   SUBSTRING(
          Field.used_artifact_fullname,
          5,
          Field.ViewNameEndPos)    as ViewName,

  key   SUBSTRING(
          Field.used_artifact_fullname,
          Field.FieldStartPos,
          100)                       as Field,

        Field.used_artifact_fullname as FullFieldName,

        CdsView.AbapViewType

}
where
  //Only fields. Fields contain \TY:<CDS view>\TY:<Field name>
  Field.IsFieldInd > 0
```
Kind regards,

Alwin.

**Comment by tschalcktwm** [comment]
Hello Alwin,

Thanks for the quick reply, now I get the following error: Expression type ATOMIC not allowed in function SUBSTRING, parameter 3 for:

  key   SUBSTRING(
          Field.used_artifact_fullname,
          5,
          Field.ViewNameEndPos)    as ViewName,

You're right, I might get other errors since my system is in a lower version than yours.

Thanks for helping.

Thibault



________________________________
De : Alwin van de Put ***@***.***>
Envoyé : mercredi 16 août 2023 13:21
À : alwinvandeput/zscv_search_cds_views ***@***.***>
Cc : SCHALCK Thibault ***@***.***>; Author ***@***.***>
Objet : Re: [alwinvandeput/zscv_search_cds_views] Installation issues (Issue #3)


CAUTION : This message comes from outside our organization. Please do not click links or open attachments unless you are sure who the sender is and know the content is safe.

Hello Thibault,

I built the query's on S/4HANA 2022, so probably that's not yet supported on version 2021.

I think we have to split that query into 2 queries, so that this part
INSTR( SUBSTRING(Field.used_artifact_fullname, 5, 100), '\\TY:') - 1
wil be calculated in a new CDS view, which will be called from the ZSCV_CdsViewSourceField.

Could you test whether the changes below works on your S/4HANA 2021 system?

define view entity ZSCV_CdsViewSourceField_Pos
  as

  select from  ddls_ris_index as Field
{
  key used_artifact_fullname,
  key ddlsrc_name,

      INSTR(SUBSTRING(Field.used_artifact_fullname,5, 100), '\\TY:') as IsFieldInd,

      INSTR(SUBSTRING(Field.used_artifact_fullname, 5, 100), '\\TY:') - 1 as ViewNameEndPos,

      INSTR(SUBSTRING(Field.used_artifact_fullname, 5, 100), '\\TY:') + 8  as FieldStartPos

}


And if that one works, adjust the ZSCV_CdsViewSourceField to

  select from  ZSCV_CdsViewSourceField_Pos as Field
    inner join ZSCV_CdsView                as CdsView on CdsView.DdlSourceName = Field.ddlsrc_name
{
  key   Field.ddlsrc_name            as DdlSourceName,

  key   SUBSTRING(
          Field.used_artifact_fullname,
          5,
          Field.ViewNameEndPos)    as ViewName,

  key   SUBSTRING(
          Field.used_artifact_fullname,
          Field.FieldStartPos,
          100)                       as Field,

        Field.used_artifact_fullname as FullFieldName,

        CdsView.AbapViewType

}
where
  //Only fields. Fields contain \TY:<CDS view>\TY:<Field name>
  Field.IsFieldInd > 0


Kind regards,

Alwin.

**Comment by alwinvandeput** [comment]
That's a unknown message to me. I could not find it in Google. We might try to convert the numbers to integers.
But I doubt whether it works. 

Could you try this?

```
define view entity ZSCV_CdsViewSourceField_Pos
  as

  select from  ddls_ris_index as Field
{
  key used_artifact_fullname,
  key ddlsrc_name,

      cast( INSTR(SUBSTRING(Field.used_artifact_fullname,5, 100), '\\TY:') as abap.int2) as IsFieldInd,

      cast( INSTR(SUBSTRING(Field.used_artifact_fullname, 5, 100), '\\TY:') - 1 as abap.int2) as ViewNameEndPos,
  
      cast(INSTR(SUBSTRING(Field.used_artifact_fullname, 5, 100), '\\TY:') + 8 as abap.int2)  as FieldStartPos
      
}
```

**Comment by alwinvandeput** [comment]
Hello Thibault,

Did the solution mentioned work on your system?

Kind regards,
Alwin

**Comment by trianta99** [comment]
I have the same issue in HANA 2021 version.

I'll try the bellow correction that you mention

define view entity ZSCV_CdsViewSourceField_Pos
  as
  select from  ddls_ris_index as Field
{
  key used_artifact_fullname,
  key ddlsrc_name,
      cast( INSTR(SUBSTRING(Field.used_artifact_fullname,5, 100), '\\TY:') as abap.int2) as IsFieldInd,
      cast( INSTR(SUBSTRING(Field.used_artifact_fullname, 5, 100), '\\TY:') - 1 as abap.int2) as ViewNameEndPos,
      cast(INSTR(SUBSTRING(Field.used_artifact_fullname, 5, 100), '\\TY:') + 8 as abap.int2)  as FieldStartPos     
}

**Comment by tschalcktwm** [comment]
Hi,

I confirm the issue is related to our S4 Hana version. I then tried to use the zscv_search_cds_views on a S4 Hana 2022 and it worked fine.

Thibault




________________________________
De : Triantafillos Parianos ***@***.***>
Envoyé : mardi 10 octobre 2023 17:19
À : alwinvandeput/zscv_search_cds_views ***@***.***>
Cc : SCHALCK Thibault ***@***.***>; Author ***@***.***>
Objet : Re: [alwinvandeput/zscv_search_cds_views] Installation issues (Issue #3)


CAUTION : This message comes from outside our organization. Please do not click links or open attachments unless you are sure who the sender is and know the content is safe.

I have the same issue in HANA 2021 version

**Comment by alwinvandeput** [comment]
I have created a new repository for < ABAP 75H.
https://github.com/alwinvandeput/zscv_search_cds_views_before_75h

I will test it next week whether it works on a system with ABAP < 75H.

**Comment by alwinvandeput** [comment]
I have tested version 2 also on a S/4HANA 2020 system. Could you please test it on your system also?
If the problem still exists, please reopen the issue.
