### ISSUE TITLE
Add the project to https://dotabap.org/

### ISSUE THREAD

**Issue by gregorwolf** [alwinvandeput/zscv_search_cds_views#4]
I would suggest that you add the project to https://dotabap.org/. Instructions can be found at https://github.com/dotabap/dotabap-list.

**Comment by alwinvandeput** [comment]
Thank you for the suggestion. I just added it to the dotabap list. I am not so familiar with Github. What I did was... create a fork, because it suggested me to do so. I changed the list.json file. And after that I pushed the button Create pull request. Hopefully it works.

**Comment by alwinvandeput** [comment]
It has been added to https://dotabap.org/.
