### ISSUE TITLE
How to search based on database table field name ?

### ISSUE THREAD

**Issue by anuragguptagithub** [alwinvandeput/zscv_search_cds_views#5]
I see this is commented 

*    SELECTION-SCREEN SKIP.

*    DATA db_field_name_type TYPE fieldname.
*    SELECT-OPTIONS s_fldnm FOR db_view_name_type NO INTERVALS.
*
*    DATA db_data_element_name_type TYPE rollname.
*    SELECT-OPTIONS s_dtelnm FOR db_data_element_name_type NO INTERVALS.
*
*    DATA db_domain_name_type TYPE domname.
*    SELECT-OPTIONS s_domnm FOR db_domain_name_type NO INTERVALS.

**Comment by alwinvandeput** [comment]
I have to do some more research whether for entity views the element name and domain name als is stored. In Version 2 it is possible to search on field name again. Sorry, for my late reaction. The reason for that is that finishing version 2 had my priority. In Version 2 you will find less CDS views, because it is more precise by searching only on the main views (sql From). 

If you have a frequently use case how you want to search for CDS views, than please let me know.

**Comment by anuragguptagithub** [comment]
Thanks for your reply. I would wait for the 2nd version then.
Basically, when consultants give me requirement, they provide me some tables and fields in SAP. My goal is to find a suitable CDS View for that. Sometimes it is easy and sometimes difficult to find.
Other point - I didn't understand the usage of super and sub entity in your solution.

Feature request : Currently CDS Dependency analyzer doesn't show all relations to base tables but only [1..1]
Is it possible to have this feature in your solution ?

**Comment by alwinvandeput** [comment]
I will go into you points.
First this one:

**Super vs Sub**
Super and sub are terms based on inheritance. Often used are that Animal is a generic type and more specific are Dog and Lion.
https://www.enjoyalgorithms.com/blog/inheritance-in-java
https://people.scs.carleton.ca/~lalonde/105WebPage/Notes/105Notes9.html

A Sales Document is a generic type and is the super type of the specific types (sub types) Sales Order, Sales Contract, and others. In SAP there is no Gui transaction to create a Sales Document and there for it is an abstract type, which means a type which can not be created and that is often the case with super types which have sub types.

**Comment by alwinvandeput** [comment]
**Find a suitable CDS**
If you are looking for a CDS view to query, than you must first look for a Released Basic CDS views. See the blog for an explanation. If not found, than a Not-released Basic CDS view. If not found, than look for all other released CDS views. If not found, than look for all CDS views. All these search actions can be executed with the tool.

**Comment by alwinvandeput** [comment]
**Version 2**
Version 2 is out  now and can be downloaded from this github repository.

**Comment by anuragguptagithub** [comment]
Thank you !!
Happy to close this issue.
