### ISSUE TITLE
S4 2023 -   SYNTAX_ERROR=>ZSCV_CDS_RELATION_INDEX_PRC===CP

### ISSUE THREAD

**Issue by TDBEOSSR** [alwinvandeput/zscv_search_cds_views#6]
Hello

we try to run the indexer program ZSCV_SEARCH_INDEXER on a s4 hana system 2023.
We get a dump.
  __Error in the ABAP application program.

   The current ABAP program "ZSCV_SEARCH_INDEXER===========CP" had to be
    terminated because it found a
   statement that could not be executed.
   In include "ZSCV_CDS_RELATION_INDEX_PRC===CM00A     ", in line 11 of program
    "ZSCV_CDS_RELATION_INDEX_PRC===CP        ", the following syntax errors
   have occurred:
   Method "GET_AST_FOR_DDLS" does not exist. There is, however, a method
   with the similar name "GET_AST_FOR_ACTIVE_DDLS".__

see attchment
![2024-02-09_12-23-04](https://github.com/alwinvandeput/zscv_search_cds_views/assets/101410626/4320fad9-bb60-438a-9a24-555f41bdb371)

From my point of view the  method  cl_qlast_utility=>get_ast_for_ddls does not exist in S4 2023
        "Now compatible with S/4HANA 2020
        DATA(lr_ddl_abstract_syntax_tree) = cl_qlast_utility=>get_ast_for_ddls(
          i_ddlsname = iv_ddl_name
          i_version  = if_dd_sobject_constants=>get_a ).

**Error Message**
Method "GET_AST_FOR_DDLS" does not exist. There is, however, a method with the similar name "GET_AST_FOR_ACTIVE_DDLS".

**Comment by alwinvandeput** [comment]
Hello, 
The code is adjusted.
Could you try it again.?
